"""Machine-readable PUE-004 normalization warnings."""

from enum import Enum


class NormalizationWarning(str, Enum):
    NUMERIC_PARSE_FAILED = "NUMERIC_PARSE_FAILED"
    DATE_PARSE_FAILED = "DATE_PARSE_FAILED"
    DATETIME_PARSE_FAILED = "DATETIME_PARSE_FAILED"
    BOOLEAN_PARSE_FAILED = "BOOLEAN_PARSE_FAILED"
    UNIT_UNKNOWN = "UNIT_UNKNOWN"
    CURRENCY_UNKNOWN = "CURRENCY_UNKNOWN"
    VALUE_TRUNCATED = "VALUE_TRUNCATED"
    UNSUPPORTED_VALUE_TYPE = "UNSUPPORTED_VALUE_TYPE"
    MAPPING_CHANGED = "MAPPING_CHANGED"
    POLICY_CONFLICT = "POLICY_CONFLICT"
    NULL_VALUE = "NULL_VALUE"
    FORMULA_VALUE_UNRESOLVED = "FORMULA_VALUE_UNRESOLVED"
