from datetime import datetime, timedelta
import logging
from pathlib import Path

from apscheduler.schedulers.background import BackgroundScheduler
from scheduler.recommendation_jobs import run_recommendations
from scheduler.ingestion_jobs import run_ingestion
from backend.services.alert_service import send_email_alert
from backend.services.report_service import (
    REPORT_SCHEDULE_TABLE,
    build_report_pdf,
    record_report_history,
)
from data.supabase_client import supabase


logger = logging.getLogger(__name__)


def _parse_datetime(value):
    if not value:
        return None

    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).replace(tzinfo=None)
    except Exception:
        return None


def _calculate_next_run(frequency, current_run=None):
    base = current_run or datetime.utcnow()
    frequency_key = str(frequency or "").lower()

    if frequency_key == "daily":
        return base + timedelta(days=1)
    if frequency_key == "weekly":
        return base + timedelta(weeks=1)
    if frequency_key == "quarterly":
        return base + timedelta(days=90)

    return base + timedelta(days=30)


def _safe_file_name(report_type, run_at):
    safe_name = (
        str(report_type or "scheduled_report")
        .lower()
        .replace("&", "and")
        .replace("/", "_")
        .replace(" ", "_")
    )
    return f"{safe_name}_{run_at.strftime('%Y%m%d_%H%M%S')}.pdf"


def run_scheduled_reports():
    now = datetime.utcnow()

    try:
        schedules = (
            supabase
            .table(REPORT_SCHEDULE_TABLE)
            .select("*")
            .eq("enabled", True)
            .execute()
            .data
            or []
        )
    except Exception as exc:
        logger.exception("scheduled_report_load_failed")
        return

    output_dir = Path("exports") / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)

    for schedule in schedules:
        next_run = _parse_datetime(schedule.get("next_run"))
        if next_run and next_run > now:
            continue

        report_type = schedule.get("report_type") or "Board Pack"
        tenant_id = schedule.get("organization_id")
        recipient = schedule.get("recipient_email")

        if not tenant_id:
            continue

        try:
            pdf_bytes = build_report_pdf(
                report_name=report_type,
                tenant_id=tenant_id,
                requested_by="scheduler",
            )
            file_name = _safe_file_name(report_type, now)
            file_path = output_dir / file_name
            file_path.write_bytes(pdf_bytes)

            email_result = send_email_alert(
                subject=f"Scheduled Report - {report_type}",
                body=(
                    f"Scheduled {report_type} generated at "
                    f"{now.strftime('%Y-%m-%d %H:%M UTC')}."
                ),
                recipients=[recipient] if recipient else [],
                attachments=[
                    {
                        "filename": file_name,
                        "content": pdf_bytes,
                        "mime_type": "application/pdf",
                    }
                ],
            )

            try:
                result = record_report_history(
                    tenant_id=tenant_id,
                    report_name=report_type,
                    requested_by="scheduler",
                    delivery_channel="scheduled",
                    status="generated",
                    file_name=file_name,
                    notes="Generated by scheduler",
                )

                if not result.get("saved"):
                    logger.error("scheduled_report_history_failed result=%s", result)

            except Exception as exc:
                logger.exception("scheduled_report_history_failed")

            supabase.table(REPORT_SCHEDULE_TABLE).update(
                {
                    "next_run": _calculate_next_run(
                        schedule.get("frequency"),
                        now,
                    ).isoformat(),
                }
            ).eq("id", schedule.get("id")).execute()

        except Exception as exc:
            logger.exception("scheduled_report_failed report_type=%s", report_type)

def start_scheduler():
    scheduler = BackgroundScheduler()

    scheduler.add_job(run_recommendations, trigger="interval", minutes=1)
    scheduler.add_job(run_ingestion, trigger="interval", minutes=1)
    scheduler.add_job(run_scheduled_reports, trigger="interval", minutes=5)

    scheduler.start()
    return scheduler


if __name__ == "__main__":
    scheduler = start_scheduler()

    try:
        import time

        while True:
            time.sleep(60)
    except (KeyboardInterrupt, SystemExit):
        scheduler.shutdown()

