"""Shared enums for canonical enterprise model contracts."""

from enum import Enum


class EntityType(str, Enum):
    """Provider-neutral canonical enterprise entity types."""

    BUSINESS_CAPABILITY = "business_capability"
    BUSINESS_SERVICE = "business_service"
    APPLICATION = "application"
    TECHNOLOGY = "technology"
    CLOUD_RESOURCE = "cloud_resource"
    SAAS_APPLICATION = "saas_application"
    VENDOR = "vendor"
    CONTRACT = "contract"
    COST_CENTER = "cost_center"
    DEPARTMENT = "department"
    OWNER = "owner"
    PROJECT = "project"
    ENVIRONMENT = "environment"
    BUSINESS_PROCESS = "business_process"
    RISK = "risk"
    RECOMMENDATION = "recommendation"
    APPROVAL = "approval"
    POLICY = "policy"
    EVIDENCE = "evidence"
    ORGANIZATION = "organization"
    BUSINESS_UNIT = "business_unit"
    PORTFOLIO = "portfolio"
    PRODUCT = "product"
    PLATFORM = "platform"
    CLOUD_ACCOUNT = "cloud_account"
    CLOUD_SUBSCRIPTION = "cloud_subscription"
    CLOUD_PROJECT = "cloud_project"
    COMPUTE_RESOURCE = "compute_resource"
    DATABASE = "database"
    STORAGE = "storage"
    NETWORK = "network"
    KUBERNETES_CLUSTER = "kubernetes_cluster"
    AI_PLATFORM = "ai_platform"
    SAAS_PRODUCT = "saas_product"
    LICENSE = "license"
    USER = "user"
    TEAM = "team"
    SPEND_SOURCE = "spend_source"
    BUDGET = "budget"
    ALLOCATION_TARGET = "allocation_target"


class RelationshipType(str, Enum):
    """Provider-neutral canonical relationship types."""

    DEPENDS_ON = "depends_on"
    RUNS_ON = "runs_on"
    OWNED_BY = "owned_by"
    SUPPLIED_BY = "supplied_by"
    FUNDS = "funds"
    IMPACTS = "impacts"
    TARGETS = "targets"
    MONITORS = "monitors"
    GOVERNS = "governs"
    APPROVES = "approves"
    EVIDENCES = "evidences"
    ASSOCIATED_WITH = "associated_with"
    OWNS = "owns"
    IMPLEMENTED_BY = "implemented_by"
    BELONGS_TO = "belongs_to"
    PRODUCES = "produces"
