"""Explicit PUE-002 ontology and alias registry; no customer-specific rules."""

from universal_evidence.contracts import EvidenceDimension, SemanticConcept
from universal_evidence.profiling import StructuralRole
from universal_evidence.semantic.models import ConceptDefinition, SemanticRisk
from universal_evidence.semantic.registry import ConceptRegistry


def _concept(
    concept_id: str,
    dimension: EvidenceDimension,
    definition: str,
    primitive_types: tuple[str, ...],
    aliases: tuple[str, ...],
    roles: tuple[StructuralRole, ...],
    risk: SemanticRisk,
    *,
    context: tuple[str, ...] = (),
    sample_shape: str | None = None,
) -> ConceptDefinition:
    return ConceptDefinition(
        SemanticConcept(
            concept_id,
            1,
            dimension,
            definition,
            primitive_types,
            aliases=aliases,
        ),
        roles,
        risk,
        context,
        sample_shape,
    )


NUMERIC = ("INTEGER", "DECIMAL")
TEXT = ("STRING",)
TEMPORAL = ("DATE", "DATETIME")
ID_ROLES = (StructuralRole.IDENTIFIER_LIKE, StructuralRole.HIGH_CARDINALITY)
MEASURE_ROLES = (StructuralRole.MEASURE_LIKE,)
DATE_ROLES = (StructuralRole.DATE_LIKE,)
CATEGORY_ROLES = (StructuralRole.CATEGORICAL_LIKE, StructuralRole.LOW_CARDINALITY)


DEFAULT_CONCEPT_REGISTRY = ConceptRegistry(
    "pue-ontology-1",
    (
        _concept(
            "financial.cost.total",
            EvidenceDimension.FINANCIAL,
            "Total monetary cost measure.",
            NUMERIC,
            ("cost", "total cost", "spend", "expense", "net cost"),
            MEASURE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("currency", "service", "account", "value"),
        ),
        _concept(
            "financial.cost.monthly",
            EvidenceDimension.FINANCIAL,
            "Monthly monetary cost measure.",
            NUMERIC,
            ("monthly cost", "monthly spend", "monthly value", "month cost"),
            MEASURE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("currency", "month", "service"),
        ),
        _concept(
            "financial.cost.unit",
            EvidenceDimension.FINANCIAL,
            "Per-unit monetary cost measure.",
            NUMERIC,
            ("unit cost", "unit price", "cost per unit"),
            MEASURE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("quantity", "unit", "currency"),
        ),
        _concept(
            "financial.currency",
            EvidenceDimension.FINANCIAL,
            "Currency code or label.",
            TEXT,
            ("currency", "currency code", "billing currency", "ccy"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            sample_shape="currency_code",
        ),
        _concept(
            "financial.price",
            EvidenceDimension.FINANCIAL,
            "Observed price measure.",
            NUMERIC,
            ("price", "rate", "list price"),
            MEASURE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("currency", "unit"),
        ),
        _concept(
            "financial.savings",
            EvidenceDimension.FINANCIAL,
            "Observed savings measure.",
            NUMERIC,
            ("savings", "saving", "discount"),
            MEASURE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("currency", "cost"),
        ),
        _concept(
            "financial.budget",
            EvidenceDimension.FINANCIAL,
            "Budget measure.",
            NUMERIC,
            ("budget", "budget amount"),
            MEASURE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("currency", "department"),
        ),
        _concept(
            "cloud.provider",
            EvidenceDimension.CLOUD,
            "Cloud provider label.",
            TEXT,
            ("provider", "cloud provider", "vendor cloud"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            sample_shape="provider_code",
        ),
        _concept(
            "cloud.account",
            EvidenceDimension.CLOUD,
            "Cloud account reference.",
            ("STRING", "INTEGER"),
            ("account", "account id", "account identifier", "acct"),
            ID_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("provider", "service", "region"),
        ),
        _concept(
            "cloud.subscription",
            EvidenceDimension.CLOUD,
            "Cloud subscription reference.",
            TEXT,
            ("subscription", "subscription id", "subscription name"),
            ID_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("provider", "resource"),
        ),
        _concept(
            "cloud.project",
            EvidenceDimension.CLOUD,
            "Cloud project reference.",
            TEXT,
            ("cloud project", "project id", "project identifier"),
            ID_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("provider", "resource"),
        ),
        _concept(
            "cloud.region",
            EvidenceDimension.CLOUD,
            "Cloud region label.",
            TEXT,
            ("cloud region", "provider region", "region"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("provider", "account", "service"),
        ),
        _concept(
            "cloud.availability_zone",
            EvidenceDimension.CLOUD,
            "Availability-zone label.",
            TEXT,
            ("availability zone", "zone", "az"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("region", "provider"),
        ),
        _concept(
            "technology.service",
            EvidenceDimension.TECHNOLOGY,
            "Technology service label.",
            TEXT,
            ("service", "service name", "cloud service", "technology service"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("resource", "provider", "region", "cost"),
        ),
        _concept(
            "technology.product",
            EvidenceDimension.TECHNOLOGY,
            "Technology product label.",
            TEXT,
            ("technology product", "product", "product name"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("vendor", "service"),
        ),
        _concept(
            "technology.platform",
            EvidenceDimension.TECHNOLOGY,
            "Technology platform label.",
            TEXT,
            ("platform", "technology platform"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("service", "application"),
        ),
        _concept(
            "technology.database",
            EvidenceDimension.TECHNOLOGY,
            "Database technology label.",
            TEXT,
            ("database", "database type", "db"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("platform", "service"),
        ),
        _concept(
            "resource.identifier",
            EvidenceDimension.RESOURCE,
            "Resource identifier.",
            ("STRING", "INTEGER"),
            (
                "resource id",
                "resource identifier",
                "resource ref",
                "resource reference",
                "id",
            ),
            ID_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("resource", "service", "region"),
        ),
        _concept(
            "resource.name",
            EvidenceDimension.RESOURCE,
            "Resource name.",
            TEXT,
            ("resource name", "resource", "asset name"),
            ID_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("service", "type"),
        ),
        _concept(
            "resource.type",
            EvidenceDimension.RESOURCE,
            "Resource type label.",
            TEXT,
            ("resource type", "asset type", "type"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("resource", "service"),
        ),
        _concept(
            "organization.business_unit",
            EvidenceDimension.ORGANIZATION,
            "Business-unit label.",
            TEXT,
            ("business unit", "bu", "org unit"),
            CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("department", "cost center"),
        ),
        _concept(
            "organization.department",
            EvidenceDimension.ORGANIZATION,
            "Department label.",
            TEXT,
            ("department", "dept", "group"),
            CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("business unit", "owner"),
        ),
        _concept(
            "organization.cost_center",
            EvidenceDimension.ORGANIZATION,
            "Cost-center reference.",
            ("STRING", "INTEGER"),
            ("cost center", "cost centre", "cc", "group"),
            ID_ROLES + CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("department", "budget"),
        ),
        _concept(
            "ownership.owner",
            EvidenceDimension.OWNERSHIP,
            "Owner identity or label.",
            TEXT,
            ("owner", "application owner", "app owner", "managed by"),
            ID_ROLES + CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("team", "application", "resource"),
        ),
        _concept(
            "ownership.team",
            EvidenceDimension.OWNERSHIP,
            "Owning or responsible team.",
            TEXT,
            ("team", "owner", "responsible team", "group"),
            CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("owner", "support"),
        ),
        _concept(
            "ownership.manager",
            EvidenceDimension.OWNERSHIP,
            "Manager identity or label.",
            TEXT,
            ("manager", "managed by"),
            ID_ROLES + CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("owner", "team"),
        ),
        _concept(
            "ownership.support_group",
            EvidenceDimension.OWNERSHIP,
            "Support-group label.",
            TEXT,
            ("support group", "support team", "group"),
            CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("owner", "service"),
        ),
        _concept(
            "application.name",
            EvidenceDimension.APPLICATION,
            "Application name.",
            TEXT,
            (
                "application",
                "application name",
                "app",
                "app name",
                "system name",
                "name",
            ),
            ID_ROLES + CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("owner", "workload", "service"),
        ),
        _concept(
            "application.workload",
            EvidenceDimension.APPLICATION,
            "Application workload label.",
            TEXT,
            ("workload", "application workload"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("application", "environment"),
        ),
        _concept(
            "application.system",
            EvidenceDimension.APPLICATION,
            "System label.",
            TEXT,
            ("system", "system name"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("application", "owner"),
        ),
        _concept(
            "business.service",
            EvidenceDimension.BUSINESS,
            "Business-service label.",
            TEXT,
            ("business service", "service"),
            CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("capability", "application"),
        ),
        _concept(
            "business.capability",
            EvidenceDimension.BUSINESS,
            "Business-capability label.",
            TEXT,
            ("business capability", "capability"),
            CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("business service", "application"),
        ),
        _concept(
            "saas.vendor",
            EvidenceDimension.SAAS,
            "SaaS vendor label.",
            TEXT,
            ("saas vendor", "vendor", "publisher"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("license", "subscription"),
        ),
        _concept(
            "saas.license_count",
            EvidenceDimension.SAAS,
            "License or seat count measure.",
            NUMERIC,
            ("license count", "licenses", "seat count", "seats", "license qty"),
            MEASURE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("vendor", "usage"),
        ),
        _concept(
            "saas.utilization",
            EvidenceDimension.SAAS,
            "SaaS utilization measure.",
            NUMERIC,
            ("usage percentage", "license utilization", "seat utilization", "util"),
            MEASURE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("license", "seat"),
        ),
        _concept(
            "saas.subscription",
            EvidenceDimension.SAAS,
            "SaaS subscription label.",
            TEXT,
            ("saas subscription", "subscription"),
            ID_ROLES + CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("vendor", "license"),
        ),
        _concept(
            "contract.identifier",
            EvidenceDimension.CONTRACT,
            "Contract identifier.",
            ("STRING", "INTEGER"),
            ("contract id", "contract identifier", "agreement id"),
            ID_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("vendor", "renewal"),
        ),
        _concept(
            "contract.start_date",
            EvidenceDimension.CONTRACT,
            "Contract start date.",
            TEMPORAL,
            ("contract start", "start date", "effective date"),
            DATE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("contract", "end date"),
        ),
        _concept(
            "contract.end_date",
            EvidenceDimension.CONTRACT,
            "Contract end date.",
            TEMPORAL,
            ("contract end", "end date", "expiry date"),
            DATE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("contract", "start date"),
        ),
        _concept(
            "contract.renewal_date",
            EvidenceDimension.CONTRACT,
            "Contract renewal date.",
            TEMPORAL,
            ("renewal", "renewal date", "renewal dt"),
            DATE_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("contract", "vendor"),
        ),
        _concept(
            "operational.cpu",
            EvidenceDimension.OPERATIONAL,
            "CPU observation measure.",
            NUMERIC,
            ("cpu", "cpu usage", "cpu percentage"),
            MEASURE_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("resource", "timestamp"),
        ),
        _concept(
            "operational.memory",
            EvidenceDimension.OPERATIONAL,
            "Memory observation measure.",
            NUMERIC,
            ("memory", "memory usage", "memory percentage"),
            MEASURE_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("resource", "timestamp"),
        ),
        _concept(
            "operational.utilization",
            EvidenceDimension.OPERATIONAL,
            "Operational utilization measure.",
            NUMERIC,
            ("utilization", "usage percentage", "util"),
            MEASURE_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("resource", "timestamp"),
        ),
        _concept(
            "operational.incident_count",
            EvidenceDimension.OPERATIONAL,
            "Incident count measure.",
            NUMERIC,
            ("incident count", "incidents"),
            MEASURE_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("service", "period"),
        ),
        _concept(
            "security.severity",
            EvidenceDimension.SECURITY,
            "Security severity label.",
            TEXT,
            ("severity", "risk severity"),
            CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("vulnerability", "control"),
        ),
        _concept(
            "security.compliance",
            EvidenceDimension.SECURITY,
            "Compliance label or status.",
            TEXT,
            ("compliance", "compliance status"),
            CATEGORY_ROLES,
            SemanticRisk.RESTRICTED,
            context=("control", "policy"),
        ),
        _concept(
            "security.control_status",
            EvidenceDimension.SECURITY,
            "Security-control status.",
            TEXT,
            ("control status", "security status", "status"),
            CATEGORY_ROLES,
            SemanticRisk.RESTRICTED,
            context=("control", "compliance"),
        ),
        _concept(
            "geography.country",
            EvidenceDimension.GEOGRAPHY,
            "Country label.",
            TEXT,
            ("country", "country code"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("location", "region"),
        ),
        _concept(
            "geography.location",
            EvidenceDimension.GEOGRAPHY,
            "Geographic location label.",
            TEXT,
            ("location", "site", "office location"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("country", "region"),
        ),
        _concept(
            "geography.region",
            EvidenceDimension.GEOGRAPHY,
            "Geographic region label.",
            TEXT,
            ("region", "geographic region"),
            CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("country", "location"),
        ),
        _concept(
            "tagging.environment",
            EvidenceDimension.TAGGING,
            "Environment tag or label.",
            TEXT,
            ("environment", "env", "stage"),
            CATEGORY_ROLES,
            SemanticRisk.LOW_RISK,
            context=("application", "resource"),
            sample_shape="environment_label",
        ),
        _concept(
            "tagging.project",
            EvidenceDimension.TAGGING,
            "Project tag or label.",
            TEXT,
            ("project", "project tag"),
            ID_ROLES + CATEGORY_ROLES,
            SemanticRisk.MODERATE_RISK,
            context=("environment", "owner"),
        ),
        _concept(
            "tagging.owner",
            EvidenceDimension.TAGGING,
            "Owner tag value.",
            TEXT,
            ("owner tag", "tag owner"),
            CATEGORY_ROLES,
            SemanticRisk.HIGH_RISK,
            context=("environment", "project"),
        ),
    ),
)
