"""Governed states shared by PUE architecture contracts."""

from enum import Enum


class EvidenceDimension(str, Enum):
    FINANCIAL = "FINANCIAL"
    CLOUD = "CLOUD"
    TECHNOLOGY = "TECHNOLOGY"
    RESOURCE = "RESOURCE"
    ORGANIZATION = "ORGANIZATION"
    OWNERSHIP = "OWNERSHIP"
    APPLICATION = "APPLICATION"
    BUSINESS = "BUSINESS"
    SAAS = "SAAS"
    CONTRACT = "CONTRACT"
    OPERATIONAL = "OPERATIONAL"
    SECURITY = "SECURITY"
    GEOGRAPHY = "GEOGRAPHY"
    TAGGING = "TAGGING"


class ClassificationState(str, Enum):
    UNCLASSIFIED = "UNCLASSIFIED"
    CANDIDATE = "CANDIDATE"
    AUTO_CLASSIFIED = "AUTO_CLASSIFIED"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    USER_CONFIRMED = "USER_CONFIRMED"
    REJECTED = "REJECTED"
    OVERRIDDEN = "OVERRIDDEN"


class ConfidenceBand(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class ConfirmationState(str, Enum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    OVERRIDDEN = "OVERRIDDEN"


class MappingAuthority(str, Enum):
    ENGINE_CLASSIFIED = "ENGINE_CLASSIFIED"
    USER_CONFIRMED = "USER_CONFIRMED"
    USER_OVERRIDDEN = "USER_OVERRIDDEN"


class AvailabilityStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    PARTIAL = "PARTIAL"
    AMBIGUOUS = "AMBIGUOUS"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    NOT_EVIDENCED = "NOT_EVIDENCED"
    UNSUPPORTED = "UNSUPPORTED"


class AggregationCapabilityState(str, Enum):
    SUPPORTED = "SUPPORTED"
    SUPPORTED_WITH_LIMITATIONS = "SUPPORTED_WITH_LIMITATIONS"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    NOT_SUPPORTED = "NOT_SUPPORTED"


class QueryCapabilityState(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    NOT_EVIDENCED = "NOT_EVIDENCED"
    NOT_SUPPORTED = "NOT_SUPPORTED"


class FusionMatchState(str, Enum):
    MATCHED = "MATCHED"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    UNMATCHED = "UNMATCHED"
    CONFLICT = "CONFLICT"
