from auth.role_constants import normalize_role

ROLE_PAGES = {
    "super_admin": [
        "Executive Dashboard",
        "Technology Portfolio Overview",
        "FinOps Dashboard",
        "Enterprise Spend",
        "Cloud Cost Imports",
        "Cloud Account Registry",
        "Cloud Connections",
        "Cost Upload Center",
        "Service Explorer",
        "Cloud Strategy",
        "Technology Portfolio",
        "Business Service Portfolio",
        "Technology Graph",
        "Technology Knowledge Graph",
        "Technology Copilot",
        "AI Copilot",
        "AI Workflow Center",
        "AI Execution Center",
        "Automation Center",
        "Enterprise Knowledge Graph",
        "Dependency Analysis",
        "Impact Analysis",
        "Simulation Center",
        "AI Reasoning Center",
        "Forecasting",
        "Risk Prediction",
        "Capacity Planning",
        "Financial Forecasting",
        "Predictive AI",
        "Prediction Performance",
        "Predictive Center",
        "Goal Center",
        "Agent Registry",
        "Multi-Agent Collaboration",
        "Workflow Designer",
        "Governance & Authorization",
        "Execution Center",
        "Learning Analytics",
        "Execution Plans",
        "Agent Console",
        "Learning Center",
        "Twin Explorer",
        "Technology Digital Twin",
        "Enterprise Digital Twin",
        "Enterprise Twin Dashboard",
        "Connector Marketplace",
        "Connector Studio",
        "Connector Health Dashboard",
        "Platform Health Dashboard",
        "Security Dashboard",
        "Performance Dashboard",
        "Compliance Dashboard",
        "Disaster Recovery Dashboard",
        "Enterprise Readiness",
        "Data Quality Dashboard",
        "Enterprise Data Fabric",
        "Entity Registry",
        "Enterprise Registry",
        "Relationship Explorer",
        "Scheduler Operations",
        "Enterprise Observability",
        "Incident Timeline",
        "Data Sources & Connectors",
        "Connector Operations",
        "AWS Onboarding Template",
        "AWS Connector Setup",
        "Azure Connector Setup",
        "TBM & Chargeback",
        "Savings Governance",
        "SaaS + AI Intelligence",
        "Technology Health & Risk",
        "Application Portfolio",
        "Business Services",
        "Technology Spend",
        "Cost Intelligence",
        "Optimization Center",
        "Leadership Dashboard",
        "Technical Analytics",
        "Operations Workspace",
        "Approvals",
        "SaaS Governance Center",
        "Audit Timeline",
        "Risk & Governance",
        "Reports",
    ],

    "client_admin": [
        "AI Copilot",
        "AI Workflow Center",
        "AI Execution Center",
        "Automation Center",
        "Enterprise Knowledge Graph",
        "Dependency Analysis",
        "Impact Analysis",
        "Simulation Center",
        "AI Reasoning Center",
        "Forecasting",
        "Risk Prediction",
        "Capacity Planning",
        "Predictive AI",
        "Prediction Performance",
        "Predictive Center",
        "Goal Center",
        "Agent Registry",
        "Multi-Agent Collaboration",
        "Workflow Designer",
        "Governance & Authorization",
        "Execution Center",
        "Learning Analytics",
        "Execution Plans",
        "Agent Console",
        "Learning Center",
        "Twin Explorer",
        "Enterprise Twin Dashboard",
        "Connector Marketplace",
        "Connector Health Dashboard",
        "Platform Health Dashboard",
        "Security Dashboard",
        "Performance Dashboard",
        "Compliance Dashboard",
        "Disaster Recovery Dashboard",
        "Enterprise Readiness",
        "Data Quality Dashboard",
        "Scheduler Operations",
        "Enterprise Observability",
        "Incident Timeline",
        "Data Sources & Connectors",
        "Connector Operations",
        "AWS Onboarding Template",
        "AWS Connector Setup",
        "Azure Connector Setup",
        "Cloud Connections",
        "Reports",
    ],

    "executive": [
        "Executive Dashboard",
        "Enterprise Spend",
        "Cloud Cost Imports",
        "Technology Knowledge Graph",
        "Technology Copilot",
        "AI Copilot",
        "AI Workflow Center",
        "AI Execution Center",
        "Automation Center",
        "Enterprise Knowledge Graph",
        "Dependency Analysis",
        "Impact Analysis",
        "Simulation Center",
        "AI Reasoning Center",
        "Forecasting",
        "Risk Prediction",
        "Capacity Planning",
        "Financial Forecasting",
        "Predictive AI",
        "Prediction Performance",
        "Predictive Center",
        "Goal Center",
        "Agent Registry",
        "Multi-Agent Collaboration",
        "Workflow Designer",
        "Governance & Authorization",
        "Execution Center",
        "Learning Analytics",
        "Execution Plans",
        "Agent Console",
        "Learning Center",
        "Twin Explorer",
        "Enterprise Digital Twin",
        "Enterprise Twin Dashboard",
        "Connector Health Dashboard",
        "Platform Health Dashboard",
        "Security Dashboard",
        "Performance Dashboard",
        "Compliance Dashboard",
        "Disaster Recovery Dashboard",
        "Enterprise Readiness",
        "Data Quality Dashboard",
        "Scheduler Operations",
        "Enterprise Observability",
        "Incident Timeline",
        "Savings Governance",
        "Approvals",
        "Reports",
    ],

    "cio": [
        "Technology Portfolio Overview",
        "Cloud Cost Imports",
        "Technology Portfolio",
        "Business Service Portfolio",
        "Technology Graph",
        "Technology Knowledge Graph",
        "Technology Copilot",
        "AI Copilot",
        "AI Workflow Center",
        "AI Execution Center",
        "Automation Center",
        "Enterprise Knowledge Graph",
        "Dependency Analysis",
        "Impact Analysis",
        "Simulation Center",
        "AI Reasoning Center",
        "Forecasting",
        "Risk Prediction",
        "Capacity Planning",
        "Financial Forecasting",
        "Predictive AI",
        "Prediction Performance",
        "Predictive Center",
        "Goal Center",
        "Agent Registry",
        "Multi-Agent Collaboration",
        "Workflow Designer",
        "Governance & Authorization",
        "Execution Center",
        "Learning Analytics",
        "Execution Plans",
        "Agent Console",
        "Learning Center",
        "Twin Explorer",
        "Technology Digital Twin",
        "Enterprise Digital Twin",
        "Enterprise Twin Dashboard",
        "Connector Marketplace",
        "Connector Health Dashboard",
        "Platform Health Dashboard",
        "Security Dashboard",
        "Performance Dashboard",
        "Compliance Dashboard",
        "Disaster Recovery Dashboard",
        "Enterprise Readiness",
        "Data Quality Dashboard",
        "Scheduler Operations",
        "Enterprise Observability",
        "Incident Timeline",
        "Data Sources & Connectors",
        "Connector Operations",
        "TBM & Chargeback",
        "Savings Governance",
        "Technology Spend",
        "Cloud Strategy",
        "Application Portfolio",
        "Technology Health & Risk",
        "SaaS + AI Intelligence",
        "Optimization Center",
        "Risk & Governance",
        "Approvals",
        "Reports",
    ],

    "finance": [
        "FinOps Dashboard",
        "Enterprise Spend",
        "Cloud Cost Imports",
        "Technology Copilot",
        "Twin Explorer",
        "Enterprise Digital Twin",
        "Enterprise Knowledge Graph",
        "Dependency Analysis",
        "Impact Analysis",
        "Simulation Center",
        "AI Reasoning Center",
        "Forecasting",
        "Risk Prediction",
        "Financial Forecasting",
        "Predictive AI",
        "Prediction Performance",
        "Predictive Center",
        "Goal Center",
        "Agent Registry",
        "Multi-Agent Collaboration",
        "Workflow Designer",
        "Governance & Authorization",
        "Execution Center",
        "Learning Analytics",
        "Execution Plans",
        "AI Execution Center",
        "TBM & Chargeback",
        "Savings Governance",
        "Technology Spend",
        "Approvals",
        "Reports",
    ],

    "technical": [
        "Operations Workspace",
        "AI Execution Center",
        "Automation Center",
        "Enterprise Knowledge Graph",
        "Dependency Analysis",
        "Impact Analysis",
        "Simulation Center",
        "AI Reasoning Center",
        "Forecasting",
        "Risk Prediction",
        "Capacity Planning",
        "Predictive AI",
        "Prediction Performance",
        "Predictive Center",
        "Goal Center",
        "Agent Registry",
        "Multi-Agent Collaboration",
        "Workflow Designer",
        "Governance & Authorization",
        "Execution Center",
        "Learning Analytics",
        "Execution Plans",
        "Agent Console",
        "Twin Explorer",
        "Technology Digital Twin",
        "Technical Analytics",
        "Connector Marketplace",
        "Connector Health Dashboard",
        "Platform Health Dashboard",
        "Security Dashboard",
        "Performance Dashboard",
        "Compliance Dashboard",
        "Disaster Recovery Dashboard",
        "Enterprise Readiness",
        "Data Quality Dashboard",
        "Scheduler Operations",
        "Enterprise Observability",
        "Incident Timeline",
        "Cloud Connections",
        "Service Explorer",
        "Cost Intelligence",
        "Risk & Governance",
        "Audit Timeline",
    ],
    "auditor": [
        "Cloud Account Registry",
        "Account Resolution",
        "Audit Timeline",
        "Reports",
    ],
    "operations": [
        "Operations Workspace",
        "Cloud Account Registry",
        "Account Resolution",
        "Service Explorer",
        "Technical Analytics",
        "Audit Timeline",
    ],
}

for _registry_role in ("super_admin", "client_admin", "executive", "finance", "cio", "auditor"):
    if _registry_role in ROLE_PAGES and "Cloud Account Registry" not in ROLE_PAGES[_registry_role]:
        ROLE_PAGES[_registry_role].append("Cloud Account Registry")

for _classification_role in (
    "super_admin", "client_admin", "executive", "finance", "cio", "operations", "auditor"
):
    if (
        _classification_role in ROLE_PAGES
        and "Account Resolution" not in ROLE_PAGES[_classification_role]
    ):
        ROLE_PAGES[_classification_role].append("Account Resolution")

PAGE_PATHS = {
    "Executive Dashboard": "pages/executive_dashboard.py",
    "Technology Portfolio Overview": "pages/cio_dashboard.py",
    "FinOps Dashboard": "pages/finance_dashboard.py",
    "Enterprise Spend": "pages/enterprise_spend.py",
    "Cloud Cost Imports": "pages/cloud_cost_imports.py",
    "Cloud Account Registry": "pages/cloud_account_registry.py",
    "Account Resolution": "pages/account_resolution.py",
    "Cloud Connections": "pages/cloud_connections.py",
    "Cost Upload Center": "pages/cost_upload_center.py",
    "Service Explorer": "pages/service_explorer.py",
    "Cloud Strategy": "pages/cloud_strategy.py",
    "Technology Portfolio": "pages/technology_inventory.py",
    "Business Service Portfolio": "pages/business_service_portfolio.py",
    "Technology Graph": "pages/technology_graph.py",
    "Technology Knowledge Graph": "pages/technology_knowledge_graph.py",
    "Technology Copilot": "pages/technology_copilot.py",
    "AI Copilot": "pages/ai_copilot.py",
    "AI Workflow Center": "pages/ai_workflow_center.py",
    "AI Execution Center": "pages/ai_execution_center.py",
    "Automation Center": "pages/automation_center.py",
    "Enterprise Knowledge Graph": "pages/enterprise_graph.py",
    "Dependency Analysis": "pages/dependency_analysis.py",
    "Impact Analysis": "pages/impact_analysis.py",
    "Simulation Center": "pages/simulation_center.py",
    "AI Reasoning Center": "pages/ai_reasoning.py",
    "Forecasting": "pages/predictive_forecasting.py",
    "Risk Prediction": "pages/risk_prediction.py",
    "Capacity Planning": "pages/capacity_planning.py",
    "Financial Forecasting": "pages/financial_forecasting.py",
    "Predictive AI": "pages/predictive_ai.py",
    "Prediction Performance": "pages/prediction_performance.py",
    "Predictive Center": "pages/predictive_center.py",
    "Goal Center": "pages/goal_center.py",
    "Agent Registry": "pages/agent_registry.py",
    "Multi-Agent Collaboration": "pages/multi_agent_collaboration.py",
    "Workflow Designer": "pages/workflow_designer.py",
    "Governance & Authorization": "pages/governance_authorization.py",
    "Execution Center": "pages/execution_center.py",
    "Learning Analytics": "pages/learning_analytics.py",
    "Execution Plans": "pages/execution_plans.py",
    "Agent Console": "pages/agent_console.py",
    "Learning Center": "pages/learning_center.py",
    "Twin Explorer": "pages/twin_explorer.py",
    "Technology Digital Twin": "pages/technology_digital_twin.py",
    "Enterprise Digital Twin": "pages/enterprise_digital_twin.py",
    "Enterprise Twin Dashboard": "pages/enterprise_digital_twin_dashboard.py",
    "Connector Marketplace": "pages/connector_marketplace.py",
    "Connector Studio": "pages/connector_studio.py",
    "Connector Health Dashboard": "pages/connector_health_dashboard.py",
    "Platform Health Dashboard": "pages/platform_health_dashboard.py",
    "Security Dashboard": "pages/security_dashboard.py",
    "Performance Dashboard": "pages/performance_dashboard.py",
    "Compliance Dashboard": "pages/compliance_dashboard.py",
    "Disaster Recovery Dashboard": "pages/disaster_recovery_dashboard.py",
    "Enterprise Readiness": "pages/enterprise_readiness.py",
    "Data Quality Dashboard": "pages/data_quality_dashboard.py",
    "Enterprise Data Fabric": "pages/enterprise_data_fabric.py",
    "Entity Registry": "pages/entity_registry.py",
    "Enterprise Registry": "pages/enterprise_registry.py",
    "Enterprise Intelligence": "pages/enterprise_intelligence.py",
    "Enterprise Search": "pages/enterprise_search.py",
    "Enterprise AI Copilot": "pages/enterprise_ai_copilot.py",
    "Decision Intelligence": "pages/decision_intelligence.py",
    "Relationship Explorer": "pages/relationship_explorer.py",
    "Scheduler Operations": "pages/scheduler_operations.py",
    "Enterprise Observability": "pages/enterprise_observability.py",
    "Incident Timeline": "pages/incident_timeline.py",
    "Data Sources & Connectors": "pages/data_sources_connectors.py",
    "Connector Operations": "pages/connector_operations.py",
    "AWS Onboarding Template": "pages/aws_onboarding_template.py",
    "AWS Connector Setup": "pages/aws_connector_setup.py",
    "Azure Connector Setup": "pages/azure_connector_setup.py",
    "SaaS + AI Intelligence": "pages/saas_intelligence.py",
    "Technology Health & Risk": "pages/technology_health.py",
    "Application Portfolio": "pages/application_inventory.py",
    "Business Services": "pages/business_services.py",
    "Technology Spend": "pages/technology_spend.py",
    "TBM & Chargeback": "pages/tbm_chargeback.py",
    "Cost Intelligence": "pages/cost_intelligence.py",
    "Optimization Center": "pages/optimization_center.py",
    "Savings Governance": "pages/savings_governance.py",
    "Leadership Dashboard": "pages/leadership_dashboard.py",
    "Technical Analytics": "pages/technical_analytics.py",
    "Operations Workspace": "pages/operations_workspace.py",
    "Approvals": "pages/approval_center.py",
    "SaaS Governance Center": "pages/saas_governance.py",
    "Audit Timeline": "pages/audit_timeline.py",
    "Risk & Governance": "pages/risk_governance.py",
    "Reports": "pages/reports.py",
}

for _enterprise_registry_role in (
    "client_admin",
    "executive",
    "cio",
    "finance",
    "auditor",
    "operations",
):
    if (
        _enterprise_registry_role in ROLE_PAGES
        and "Enterprise Registry" not in ROLE_PAGES[_enterprise_registry_role]
    ):
        ROLE_PAGES[_enterprise_registry_role].append("Enterprise Registry")

for _relationship_role in (
    "client_admin",
    "executive",
    "cio",
    "finance",
    "auditor",
    "operations",
):
    if "Relationship Explorer" not in ROLE_PAGES[_relationship_role]:
        ROLE_PAGES[_relationship_role].append("Relationship Explorer")

for _intelligence_role in (
    "super_admin",
    "client_admin",
    "executive",
    "cio",
    "finance",
    "auditor",
    "operations",
):
    if "Enterprise Intelligence" not in ROLE_PAGES[_intelligence_role]:
        ROLE_PAGES[_intelligence_role].append("Enterprise Intelligence")
    if "Enterprise Search" not in ROLE_PAGES[_intelligence_role]:
        ROLE_PAGES[_intelligence_role].append("Enterprise Search")
    if "Enterprise AI Copilot" not in ROLE_PAGES[_intelligence_role]:
        ROLE_PAGES[_intelligence_role].append("Enterprise AI Copilot")
    if "Decision Intelligence" not in ROLE_PAGES[_intelligence_role]:
        ROLE_PAGES[_intelligence_role].append("Decision Intelligence")

DEFAULT_ROLE_PAGE = {
    "super_admin": PAGE_PATHS["Executive Dashboard"],
    "executive": PAGE_PATHS["Executive Dashboard"],
    "cio": PAGE_PATHS["Technology Portfolio Overview"],
    "finance": PAGE_PATHS["FinOps Dashboard"],
    "technical": PAGE_PATHS["Operations Workspace"],
    "operations": PAGE_PATHS["Operations Workspace"],
    "auditor": PAGE_PATHS["Audit Timeline"],
}


def get_role_pages(role: str):
    normalized_role = normalize_role(role)
    return ROLE_PAGES.get(normalized_role, [])


def render_sidebar_navigation(role: str):
    from components.navigation.sidebar import render_enterprise_sidebar

    return render_enterprise_sidebar(
        role,
        page_paths=PAGE_PATHS,
        role_pages=ROLE_PAGES,
    )
