-- CMP-P6-DEF-001: reconstructed prerequisites of the dated public chain.
-- SCHEMA ONLY. New empty public application schema only. Run as postgres.
-- This is NOT a complete application bootstrap: see the BLOCKED manifest at
-- docs/cmp/CMP-P6-DEF-001/migration_manifest.json before any deployment.
-- Never replay historical dumps or tenant backfills alongside this file.
begin;

do $$
begin
    if exists (
        select 1 from pg_catalog.pg_class c
        join pg_catalog.pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public' and c.relkind in ('r', 'p', 'v', 'm', 'S')
          and not exists (
              select 1 from pg_catalog.pg_depend d
              where d.classid = 'pg_catalog.pg_class'::regclass
                and d.objid = c.oid and d.deptype = 'e'
          )
    ) then
        raise exception 'Prerequisite bootstrap requires an empty public application schema';
    end if;
end;
$$;

-- Source: backups/schema_v1.sql organizations definition, PK and FK targets.
create table public.organizations (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    created_at timestamp without time zone default now(),
    status text default 'active'
);

-- Source: backups/schema_v1.sql users definition, users_email_key and org FK.
-- Preserve UUID organization identity; do not infer identity from JWT metadata.
create table public.users (
    id uuid primary key default gen_random_uuid(),
    email text not null unique,
    name text,
    role text,
    org_id uuid references public.organizations(id),
    created_at timestamp without time zone default now()
);

-- Source: backups/schema_v1.sql clients definition, PK and org FK.
create table public.clients (
    id uuid primary key default gen_random_uuid(),
    name text,
    industry text,
    region text,
    created_at timestamp without time zone default now(),
    org_id uuid references public.organizations(id)
);

-- Source: backups/schema_v1.sql recommendations definition, PK and org FK.
-- client_id had no FK in that source; do not invent one here.
create table public.recommendations (
    id uuid primary key default gen_random_uuid(),
    org_id uuid references public.organizations(id),
    service text,
    description text,
    estimated_savings numeric,
    status text default 'pending',
    created_at timestamp without time zone default now(),
    client_id uuid,
    type text,
    message text,
    impact text,
    resolved_at timestamp without time zone,
    completed_at timestamp without time zone
);

-- Source: supabase/reporting_tables.sql; preserve text scope columns.
create table public.report_history (
    id uuid primary key,
    org_id text,
    tenant_id text,
    report_name text not null,
    requested_by text,
    delivery_channel text,
    status text,
    recipients jsonb not null default '[]'::jsonb,
    file_name text,
    notes text,
    created_at timestamptz not null default now()
);
create index idx_report_history_org_created on public.report_history (org_id, created_at desc);
create unique index idx_report_history_id on public.report_history (id);

-- NEXORA_V1_APPROVAL_AUTHORITY: explicit tenant-scoped approval persistence.
create table public.nexora_v1_approval_requests (
    request_id text primary key default gen_random_uuid()::text,
    compatibility_id bigint generated by default as identity,
    organization_id text not null,
    tenant_id text not null,
    subject_id text not null,
    requested_action text not null,
    state text not null default 'PENDING'
        check (state in ('PENDING', 'APPROVED', 'REJECTED', 'ESCALATED', 'COMPLETED', 'CLOSED')),
    workflow_stage text not null default 'FINANCE'
        check (workflow_stage in ('FINANCE', 'CIO', 'CEO')),
    current_approver_role text not null default 'finance',
    requesting_actor text not null,
    decision_actor text,
    reason text not null,
    created_at timestamptz not null default now(),
    decision_at timestamptz,
    escalated_to text,
    unique (organization_id, tenant_id, compatibility_id)
);
create index nexora_v1_approval_requests_scope_idx
    on public.nexora_v1_approval_requests (organization_id, tenant_id, state, created_at desc);

create table public.nexora_v1_approval_history (
    history_id uuid primary key default gen_random_uuid(),
    request_id text not null references public.nexora_v1_approval_requests(request_id),
    organization_id text not null,
    tenant_id text not null,
    from_state text not null,
    to_state text not null,
    actor text not null,
    action text not null default 'TRANSITION',
    actor_role text,
    reason text not null,
    occurred_at timestamptz not null default now()
);
create index nexora_v1_approval_history_scope_idx
    on public.nexora_v1_approval_history (organization_id, tenant_id, request_id, occurred_at);

-- Fail closed until the next, unchanged security migration creates policies.
alter table public.organizations enable row level security;
alter table public.users enable row level security;
alter table public.clients enable row level security;
alter table public.recommendations enable row level security;
alter table public.report_history enable row level security;
alter table public.nexora_v1_approval_requests enable row level security;
alter table public.nexora_v1_approval_history enable row level security;
revoke all on public.organizations, public.users, public.clients,
    public.recommendations, public.report_history,
    public.nexora_v1_approval_requests, public.nexora_v1_approval_history
    from public, anon, authenticated;
grant usage on schema public to authenticated, service_role;
grant select on public.organizations, public.users, public.clients to authenticated;
grant select, insert on public.recommendations, public.report_history to authenticated;
grant select, insert, update, delete on public.organizations, public.users,
    public.clients, public.recommendations, public.report_history to service_role;
grant select, insert, update on public.nexora_v1_approval_requests to service_role;
grant select, insert on public.nexora_v1_approval_history to service_role;

commit;
