SUPABASE_URL = "https://iafrrtmvvqmuksvprrsj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhZnJydG12dnFtdWtzdnBycnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNDk2NjYsImV4cCI6MjA5MDcyNTY2Nn0.usksXMDPcdmfTjfeI-8eZoEkYPvQtjhfVBLqekSBwYU"
